### ISSUE TITLE
Anchored PCR primer design

### ISSUE THREAD

**Issue by timoha15** [aakechin/NGS-PrimerPlex#11]
Hi!
I am planning to construct primers for targeted RNAseq, where I use anchored oligo dT primer to target all polyA+ transcripts (Lexogen Quantseq Flex protocol). Thus I will only need a custom forward gene-specific primers to target a region proximal to the 3'-end of transcripts (3'-UTR).
For NGS-primerplex.py (I run it on unix through the command-line; GRCm38.p6 used as a reference genome) I provide:
1) regions.csv file with the coordinates of 3'-UTR of each gene (a region of 250-300 bp) and telling that I need only L primer.
2) Sequence of the adaptors: -ad1 gttcagacgtgtgctcttccgatct, -ad2 cacgacgctcttccgatct
3) Amplicon length: -minampllen 150, -optampllen 230 and -maxampllen 300. 
All the other parameters are kept at the default state.

However, the program designs a couple of L primers per gene (sometimes even outside of the range defined in regions.csv) and as a product length always indicates 300 (which is maxampllen) and this does not make any sense as, sometimes, the distance from the primer to the polyA tail is less than 100 nt.

I was wondering how exactly the program designs primers for anchored PCR and what I could change/improve in order to design the primers for my purpose?

Thank you in advance for your time and help!

P.S. Please let me know if any information/data is missing and I will add it. I am new to github and not very familiar with a common way to ask questions here 😀

**Comment by aakechin** [comment]
@timoha15 Thank you for your question! The function of designing primers for anchored PCR is a little ridiculous because primer3 package always creates both (left and right) primers but outputs only one. And since the function is based on the primer3, NGS-PrimerPlex works the same way.
However despite this, the function should work. I think that in your case the problem is that the target region is not a region which will contain primer. It is a region between two primers or as in your case after a left primer. So if you need to place primer e.g. 150 bp from the polyA, write target region as <polyA coordinates minus ~120bp> to polyA coordinates.
The NGS-PrimerPlex designed two primers because it could not cover whole target region (region between primers) by the defined amplicon length. To restrict it to one amplicon you can use 'W' in the input file with target regions (see the manual).
Try this. If there are new questions, do not hesitate to contact me again!

**Comment by timoha15** [comment]
Hi!
Another question to this topic: for some genes program designs reverse primer beyond the coordinates that are indicated in the regions.csv file (even when, following your recommendation, a region was limited to 120nt and W option was set; "write target region as <polyA coordinates minus ~120bp> to polyA coordinates.").
Placement of the reverse primer beyond the polyA coordinates and beyond the actual 3'end will cause a big problem, as original RNA does not have this sequence, so no product will be produced. Is it possible to somehow adjust the program, so that it makes primers only in the defined region from csv file? Or, alternatively, if the primer could not be designed for the indicated region, then no-primers will be produced, to avoid the case described above?

Thank you in advance for your time and help!

**Comment by aakechin** [comment]
@timoha15 Unfortunately, in the NGS-PrimerPlex there is no ways to avoid some regions for primer design directly. However, I see two ways to avoid it indirectly:
- Use of transcripts as "reference genome"
- Precise calculation of target region coordinates and amplicon lengths in such a way that the right primer will not be placed in the 3'-UTR. For example, you can use the following values:
the length of the taregt region - 100 bp and it is used with "W";
the gap between target region and 3'-UTR - 100 bp (it can be set by the target region coordinates);
the maximal amplicon length - 200 bp.
With this parameters, the right primer cannot be placed in the 3'-UTR:
--------->|-----------------------------|-------------------<-----------------|----------------------
Left (~20nt)     target region (100bp)   left gap (70 bp)    Right (~30 bp)      3'-UTR
Since the left primer with target region take 120 bp, the left amplicon length 80 bp will be obviously less than the gap length defined (100 bp), and the right primer will not be in the 3'-UTR region.
